java_version=21
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=anvilcraftappliedgrid
mod_name=AnvilCraft Applied Grid
mod_license=MIT
mod_version=0.0.1
maven_group=com.renzaifei.anvilcraftappliedgrid
mod_authors=renzaifei
mod_description=An addon for AnvilCraft that seamlessly integrates Applied Energistics 2 devices into the AnvilCraft power grid system.
