name: Upload Release Asset
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: release
      VERSION_TYPE: ${{ github.event.release.prerelease && 'beta' || 'release' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Read Properties
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_id mod_name java_version modrinth_id upload mod_version minecraft_version'

      - name: Setup Java ${{ steps.properties.outputs.java_version }}
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: ${{ steps.properties.outputs.java_version }}

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v4.3.1

      - name: Build
        run: ./gradlew build

      - name: Get Version
        id: version
        run: |
          echo "version=${{ steps.properties.outputs.mod_version }}" >> $GITHUB_OUTPUT
          echo "jar=build/libs/${{ steps.properties.outputs.mod_id }}-${{ steps.properties.outputs.minecraft_version }}-${{ steps.properties.outputs.mod_version }}.jar" >> $GITHUB_OUTPUT

      - name: Verify jar exists
        run: ls -l '${{ steps.version.outputs.jar }}'

      - name: capture build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "${{ steps.properties.outputs.mod_name }} ${{ steps.version.outputs.version }}"
          path: ${{ steps.version.outputs.jar }}
          if-no-files-found: error

      - name: Upload Release Jar
        run: |
          gh release upload '${{ github.event.release.tag_name }}' \
            '${{ steps.version.outputs.jar }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish neoforge mc mod
        uses: Kir-Antipov/mc-publish@v3.3
        if: ${{ steps.properties.outputs.upload }}
        continue-on-error: true
        with:
          name: "${{ steps.properties.outputs.mod_name }} For NeoForge v${{ steps.version.outputs.version }}"
          version: ${{ steps.version.outputs.version }}
          game-versions: 1.21.1
          version-type: ${{ env.VERSION_TYPE }}
          java: 21
          fail-mode: skip
          changelog: ${{ github.event.release.body }}

          modrinth-id: ${{ steps.properties.outputs.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true

          dependencies: |
            anvilcraft@1.21.1-1.6.0(required){modrinth:vuISAWPc}

          files: |
            ${{ steps.version.outputs.jar }}
